apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-deployment.yaml
  - azure-file-csi-deployment.yaml
  - namespace.yaml
  - configuration/pvclaim_onpremise.yaml
  #-/configuration/pvclaim_azure_nfs.yaml
  - log4net_config.yaml
  - root-user-details.yaml
  - version-config.yaml
  - branding_config.yaml
  - license-key-secret.yaml
  - bingmap-secrets.yaml
  - db-server-secret.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
